/**
 * Private Download Route
 *
 * URL: /api/download/{signed_token}
 *
 * The signed token is generated by the webhook handler on payment_intent.succeeded.
 * Each purchase gets its own unique 30-day token. No filesystem access.
 * ZIP is fetched from Vercel Blob Storage on demand.
 *
 * GET /api/download/{token}        → HTML download page (auto-triggers download)
 * GET /api/download/{token}?file=1 → Raw ZIP stream
 */

import { NextRequest, NextResponse } from "next/server";
import { verifyDownloadToken } from "@/lib/download-token";

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ token: string }> }
) {
  const { token } = await params;

  const payload = verifyDownloadToken(token);
  if (!payload) {
    return new NextResponse(
      `<!DOCTYPE html><html><body style="font-family:Arial;padding:40px;text-align:center">
        <h2 style="color:#dc2626">Download link invalid or expired</h2>
        <p>This link may have expired (links are valid for 30 days).</p>
        <p>Email <a href="mailto:thestartergroupenterprise@gmail.com">thestartergroupenterprise@gmail.com</a> and we'll resend it.</p>
      </body></html>`,
      { status: 404, headers: { "Content-Type": "text/html; charset=utf-8" } }
    );
  }

  // ?file=1 → stream the raw ZIP from Vercel Blob
  const url = new URL(req.url);
  if (url.searchParams.get("file") === "1") {
    let blobRes: Response;
    try {
      blobRes = await fetch(payload.url);
      if (!blobRes.ok) throw new Error(`Blob returned ${blobRes.status}`);
    } catch (err) {
      console.error("[download] Blob fetch failed:", err);
      return NextResponse.json(
        { error: "File temporarily unavailable. Please try again or contact support." },
        { status: 503 }
      );
    }

    const zipBuffer = Buffer.from(await blobRes.arrayBuffer());

    return new NextResponse(zipBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": 'attachment; filename="Etsy-IP-Defense-Kit.zip"',
        "Cache-Control": "no-store",
        "X-Content-Type-Options": "nosniff",
      },
    });
  }

  // Default → HTML download page with fetch+blob auto-download
  const fileUrl = `/api/download/${token}?file=1`;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Downloading your Etsy IP Defense Kit…</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: Arial, sans-serif;
      background: #fffbeb;
      display: flex;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      padding: 24px;
    }
    .card {
      background: white;
      border-radius: 12px;
      padding: 48px 40px;
      max-width: 520px;
      width: 100%;
      text-align: center;
      box-shadow: 0 4px 24px rgba(0,0,0,0.08);
    }
    .icon { font-size: 48px; margin-bottom: 16px; }
    h1 { color: #111; font-size: 22px; margin-bottom: 12px; }
    p { color: #555; font-size: 15px; line-height: 1.6; margin-bottom: 20px; }
    .btn {
      display: inline-block;
      background: #f59e0b;
      color: white;
      padding: 14px 28px;
      border-radius: 8px;
      text-decoration: none;
      font-size: 16px;
      font-weight: bold;
      margin-top: 8px;
      cursor: pointer;
      border: none;
    }
    .btn:hover { background: #d97706; }
    .status { font-size: 14px; color: #16a34a; margin-top: 16px; min-height: 20px; }
    .note { font-size: 13px; color: #999; margin-top: 24px; }
  </style>
</head>
<body>
  <div class="card">
    <div class="icon">📦</div>
    <h1>Your download is starting…</h1>
    <p>Your <strong>Etsy IP Defense Kit</strong> (5 PDF documents) should download automatically.<br>
    If nothing happens after a few seconds, click the button below.</p>
    <a id="dlBtn" class="btn" href="${fileUrl}">
      ⬇ Download Now
    </a>
    <div class="status" id="status"></div>
    <p class="note">
      Questions? Email us at
      <a href="mailto:thestartergroupenterprise@gmail.com" style="color:#d97706;">
        thestartergroupenterprise@gmail.com
      </a>
    </p>
  </div>
  <script>
    var FILE_URL = '${fileUrl}';
    var btn = document.getElementById('dlBtn');
    var status = document.getElementById('status');

    function triggerDownload() {
      status.textContent = 'Preparing download…';
      fetch(FILE_URL)
        .then(function(res) {
          if (!res.ok) throw new Error('Server returned ' + res.status);
          return res.blob();
        })
        .then(function(blob) {
          var objectUrl = URL.createObjectURL(blob);
          var a = document.createElement('a');
          a.href = objectUrl;
          a.download = 'Etsy-IP-Defense-Kit.zip';
          document.body.appendChild(a);
          a.click();
          document.body.removeChild(a);
          setTimeout(function() { URL.revokeObjectURL(objectUrl); }, 10000);
          status.textContent = '✓ Download started! Check your Downloads folder.';
        })
        .catch(function(err) {
          console.error('Download error:', err);
          status.textContent = '';
          window.location.href = FILE_URL;
        });
    }

    btn.addEventListener('click', function(e) {
      e.preventDefault();
      triggerDownload();
    });

    setTimeout(triggerDownload, 600);
  </script>
</body>
</html>`;

  return new NextResponse(html, {
    status: 200,
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "no-store",
    },
  });
}
