/**
 * Private Download Route
 * Serves the ZIP bundle at a secret URL path.
 * URL format: /api/download/[DOWNLOAD_SECRET_PATH]
 *
 * The token in the URL is compared to the DOWNLOAD_SECRET_PATH env variable.
 * If it matches, the ZIP is served. If not, 404.
 *
 * The ZIP file must be placed at: /public/downloads/etsy-ip-defense-kit.zip
 * (generated by scripts/build-pdf-bundle.sh)
 */

import { NextRequest, NextResponse } from "next/server";
import { readFile } from "fs/promises";
import path from "path";

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ token: string }> }
) {
  const { token } = await params;
  const secretPath = process.env.DOWNLOAD_SECRET_PATH;

  if (!secretPath) {
    return NextResponse.json({ error: "Download not configured" }, { status: 500 });
  }

  if (token !== secretPath) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  // Serve the ZIP file
  try {
    const filePath = path.join(process.cwd(), "public", "downloads", "etsy-ip-defense-kit.zip");
    const fileBuffer = await readFile(filePath);

    return new NextResponse(fileBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": 'attachment; filename="Etsy-IP-Defense-Kit.zip"',
        "Cache-Control": "no-store",
      },
    });
  } catch {
    console.error("[download] ZIP file not found at expected path");
    return NextResponse.json({ error: "File not available" }, { status: 500 });
  }
}
